services:
  db:
    image: postgres:latest
    container_name: metanavit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: metanavit
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./metanavit_db.sql:/docker-entrypoint-initdb.d/metanavit_db.sql
  ollama:
    image: ollama/ollama:latest  # Replace with your Ollama Docker image name
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /Users/tanish/Downloads/CODE/capstone/MetaNaviT/LLMS:/root/.ollama

volumes:
  postgres_data:
