file_system:
  # Base directory to start crawling from
  path: "data"
  # Optional crawler settings
  max_workers: 4
  batch_size: 1000
  # Optional file exclusion patterns
  exclude:
    - "**/*.git/*"
    - "**/*.pyc"
    - "**/node_modules/*"
    - "**/__pycache__/*"
#db:
  # connection: connection string
  # queries: list of queries to run