name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/backend-app.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.11'
        activate-environment: metanavit
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate metanavit
        pip install -r requirements.txt
        pip install -U deepeval
        pip install pytest pytest-asyncio pytest-cov pytest-mock


    - name: Run Tests
      shell: bash -l {0}
      run: |
        conda activate metanavit
        pytest tests/unit_tests 

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install flake8
      run: pip install flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names

        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501,W292,W293
    - name: Test with pytest
      run: |
        poetry run pytest --ignore=llm_benchmark_tests
