name: Backend CI

on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/backend-app.yml'
    branches: [ main ]

  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.11'
        activate-environment: metanavit
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        ./scripts/setup.sh


    - name: Run Tests
      shell: bash -l {0}
      run: |
        pip install pytest pytest-asyncio pytest-cov pytest-mock
        conda activate metanavit
        pytest tests/unit_tests 

